\i query_explain/queries_10/query_0.sql \t on 
\i query_explain/queries_10/query_1.sql \t on 
\i query_explain/queries_10/query_2.sql \t on 
\i query_explain/queries_10/query_3.sql \t on 
\i query_explain/queries_10/query_4.sql \t on 
\i query_explain/queries_10/query_5.sql \t on 
\i query_explain/queries_10/query_6.sql \t on 
\i query_explain/queries_10/query_7.sql \t on 
\i query_explain/queries_10/query_8.sql \t on 
\i query_explain/queries_10/query_9.sql \t on 
\i query_explain/queries_10/query_10.sql \t on 
\i query_explain/queries_10/query_11.sql \t on 
\i query_explain/queries_10/query_12.sql \t on 
\i query_explain/queries_10/query_13.sql \t on 
\i query_explain/queries_10/query_14.sql \t on 
\i query_explain/queries_10/query_15.sql \t on 
\i query_explain/queries_10/query_16.sql \t on 
\i query_explain/queries_10/query_17.sql \t on 
\i query_explain/queries_10/query_18.sql \t on 
\i query_explain/queries_10/query_19.sql \t on 
\i query_explain/queries_10/query_20.sql \t on 
\i query_explain/queries_10/query_21.sql \t on 
\i query_explain/queries_10/query_22.sql \t on 
\i query_explain/queries_10/query_23.sql \t on 
\i query_explain/queries_10/query_24.sql \t on 
\i query_explain/queries_10/query_25.sql \t on 
\i query_explain/queries_10/query_26.sql \t on 
\i query_explain/queries_10/query_27.sql \t on 
\i query_explain/queries_10/query_28.sql \t on 
\i query_explain/queries_10/query_29.sql \t on 
\i query_explain/queries_10/query_30.sql \t on 
\i query_explain/queries_10/query_31.sql \t on 
\i query_explain/queries_10/query_32.sql \t on 
\i query_explain/queries_10/query_33.sql \t on 
\i query_explain/queries_10/query_34.sql \t on 
\i query_explain/queries_10/query_35.sql \t on 
\i query_explain/queries_10/query_36.sql \t on 
\i query_explain/queries_10/query_37.sql \t on 
\i query_explain/queries_10/query_38.sql \t on 
\i query_explain/queries_10/query_39.sql \t on 
\i query_explain/queries_10/query_40.sql \t on 
\i query_explain/queries_10/query_41.sql \t on 
\i query_explain/queries_10/query_42.sql \t on 
\i query_explain/queries_10/query_43.sql \t on 
\i query_explain/queries_10/query_44.sql \t on 
\i query_explain/queries_10/query_45.sql \t on 
\i query_explain/queries_10/query_46.sql \t on 
\i query_explain/queries_10/query_47.sql \t on 
\i query_explain/queries_10/query_48.sql \t on 
\i query_explain/queries_10/query_49.sql \t on 
\i query_explain/queries_10/query_50.sql \t on 
\i query_explain/queries_10/query_51.sql \t on 
\i query_explain/queries_10/query_52.sql \t on 
\i query_explain/queries_10/query_53.sql \t on 
\i query_explain/queries_10/query_54.sql \t on 
\i query_explain/queries_10/query_55.sql \t on 
\i query_explain/queries_10/query_56.sql \t on 
\i query_explain/queries_10/query_57.sql \t on 
\i query_explain/queries_10/query_58.sql \t on 
\i query_explain/queries_10/query_59.sql \t on 
\i query_explain/queries_10/query_60.sql \t on 
\i query_explain/queries_10/query_61.sql \t on 
\i query_explain/queries_10/query_62.sql \t on 
\i query_explain/queries_10/query_63.sql \t on 
\i query_explain/queries_10/query_64.sql \t on 
\i query_explain/queries_10/query_65.sql \t on 
\i query_explain/queries_10/query_66.sql \t on 
\i query_explain/queries_10/query_67.sql \t on 
\i query_explain/queries_10/query_68.sql \t on 
\i query_explain/queries_10/query_69.sql \t on 
\i query_explain/queries_10/query_70.sql \t on 
\i query_explain/queries_10/query_71.sql \t on 
\i query_explain/queries_10/query_72.sql \t on 
\i query_explain/queries_10/query_73.sql \t on 
\i query_explain/queries_10/query_74.sql \t on 
\i query_explain/queries_10/query_75.sql \t on 
\i query_explain/queries_10/query_76.sql \t on 
\i query_explain/queries_10/query_77.sql \t on 
\i query_explain/queries_10/query_78.sql \t on 
\i query_explain/queries_10/query_79.sql \t on 
\i query_explain/queries_10/query_80.sql \t on 
\i query_explain/queries_10/query_81.sql \t on 
\i query_explain/queries_10/query_82.sql \t on 
\i query_explain/queries_10/query_83.sql \t on 
\i query_explain/queries_10/query_84.sql \t on 
\i query_explain/queries_10/query_85.sql \t on 
\i query_explain/queries_10/query_86.sql \t on 
\i query_explain/queries_10/query_87.sql \t on 
\i query_explain/queries_10/query_88.sql \t on 
\i query_explain/queries_10/query_89.sql \t on 
\i query_explain/queries_10/query_90.sql \t on 
\i query_explain/queries_10/query_91.sql \t on 
\i query_explain/queries_10/query_92.sql \t on 
\i query_explain/queries_10/query_93.sql \t on 
\i query_explain/queries_10/query_94.sql \t on 
\i query_explain/queries_10/query_95.sql \t on 
\i query_explain/queries_10/query_96.sql \t on 
\i query_explain/queries_10/query_97.sql \t on 
\i query_explain/queries_10/query_98.sql \t on 
