\o ../../analyze/analyze_0.json
\i query_0.sql
\o ../../analyze/analyze_1.json
\i query_1.sql
\o ../../analyze/analyze_2.json
\i query_2.sql
\o ../../analyze/analyze_3.json
\i query_3.sql
\o ../../analyze/analyze_4.json
\i query_4.sql
\o ../../analyze/analyze_5.json
\i query_5.sql
\o ../../analyze/analyze_6.json
\i query_6.sql
\o ../../analyze/analyze_7.json
\i query_7.sql
\o ../../analyze/analyze_8.json
\i query_8.sql
\o ../../analyze/analyze_9.json
\i query_9.sql
\o ../../analyze/analyze_10.json
\i query_10.sql
\o ../../analyze/analyze_11.json
\i query_11.sql
\o ../../analyze/analyze_12.json
\i query_12.sql
\o ../../analyze/analyze_13.json
\i query_13.sql
\o ../../analyze/analyze_14.json
\i query_14.sql
\o ../../analyze/analyze_15.json
\i query_15.sql
\o ../../analyze/analyze_16.json
\i query_16.sql
\o ../../analyze/analyze_17.json
\i query_17.sql
\o ../../analyze/analyze_18.json
\i query_18.sql
\o ../../analyze/analyze_19.json
\i query_19.sql
\o ../../analyze/analyze_20.json
\i query_20.sql
\o ../../analyze/analyze_21.json
\i query_21.sql
\o ../../analyze/analyze_22.json
\i query_22.sql
\o ../../analyze/analyze_23.json
\i query_23.sql
\o ../../analyze/analyze_24.json
\i query_24.sql
\o ../../analyze/analyze_25.json
\i query_25.sql
\o ../../analyze/analyze_26.json
\i query_26.sql
\o ../../analyze/analyze_27.json
\i query_27.sql
\o ../../analyze/analyze_28.json
\i query_28.sql
\o ../../analyze/analyze_29.json
\i query_29.sql
\o ../../analyze/analyze_30.json
\i query_30.sql
\o ../../analyze/analyze_31.json
\i query_31.sql
\o ../../analyze/analyze_32.json
\i query_32.sql
\o ../../analyze/analyze_33.json
\i query_33.sql
\o ../../analyze/analyze_34.json
\i query_34.sql
\o ../../analyze/analyze_35.json
\i query_35.sql
\o ../../analyze/analyze_36.json
\i query_36.sql
\o ../../analyze/analyze_37.json
\i query_37.sql
\o ../../analyze/analyze_38.json
\i query_38.sql
\o ../../analyze/analyze_39.json
\i query_39.sql
\o ../../analyze/analyze_40.json
\i query_40.sql
\o ../../analyze/analyze_41.json
\i query_41.sql
\o ../../analyze/analyze_42.json
\i query_42.sql
\o ../../analyze/analyze_43.json
\i query_43.sql
\o ../../analyze/analyze_44.json
\i query_44.sql
\o ../../analyze/analyze_45.json
\i query_45.sql
\o ../../analyze/analyze_46.json
\i query_46.sql
\o ../../analyze/analyze_47.json
\i query_47.sql
\o ../../analyze/analyze_48.json
\i query_48.sql
\o ../../analyze/analyze_49.json
\i query_49.sql
\o ../../analyze/analyze_50.json
\i query_50.sql
\o ../../analyze/analyze_51.json
\i query_51.sql
\o ../../analyze/analyze_52.json
\i query_52.sql
\o ../../analyze/analyze_53.json
\i query_53.sql
\o ../../analyze/analyze_54.json
\i query_54.sql
\o ../../analyze/analyze_55.json
\i query_55.sql
\o ../../analyze/analyze_56.json
\i query_56.sql
\o ../../analyze/analyze_57.json
\i query_57.sql
\o ../../analyze/analyze_58.json
\i query_58.sql
\o ../../analyze/analyze_59.json
\i query_59.sql
\o ../../analyze/analyze_60.json
\i query_60.sql
\o ../../analyze/analyze_61.json
\i query_61.sql
\o ../../analyze/analyze_62.json
\i query_62.sql
\o ../../analyze/analyze_63.json
\i query_63.sql
\o ../../analyze/analyze_64.json
\i query_64.sql
\o ../../analyze/analyze_65.json
\i query_65.sql
\o ../../analyze/analyze_66.json
\i query_66.sql
\o ../../analyze/analyze_67.json
\i query_67.sql
\o ../../analyze/analyze_68.json
\i query_68.sql
\o ../../analyze/analyze_69.json
\i query_69.sql
\o ../../analyze/analyze_70.json
\i query_70.sql
\o ../../analyze/analyze_71.json
\i query_71.sql
\o ../../analyze/analyze_72.json
\i query_72.sql
\o ../../analyze/analyze_73.json
\i query_73.sql
\o ../../analyze/analyze_74.json
\i query_74.sql
\o ../../analyze/analyze_75.json
\i query_75.sql
\o ../../analyze/analyze_76.json
\i query_76.sql
\o ../../analyze/analyze_77.json
\i query_77.sql
\o ../../analyze/analyze_78.json
\i query_78.sql
\o ../../analyze/analyze_79.json
\i query_79.sql
\o ../../analyze/analyze_80.json
\i query_80.sql
\o ../../analyze/analyze_81.json
\i query_81.sql
\o ../../analyze/analyze_82.json
\i query_82.sql
\o ../../analyze/analyze_83.json
\i query_83.sql
\o ../../analyze/analyze_84.json
\i query_84.sql
\o ../../analyze/analyze_85.json
\i query_85.sql
\o ../../analyze/analyze_86.json
\i query_86.sql
\o ../../analyze/analyze_87.json
\i query_87.sql
\o ../../analyze/analyze_88.json
\i query_88.sql
\o ../../analyze/analyze_89.json
\i query_89.sql
\o ../../analyze/analyze_90.json
\i query_90.sql
\o ../../analyze/analyze_91.json
\i query_91.sql
\o ../../analyze/analyze_92.json
\i query_92.sql
\o ../../analyze/analyze_93.json
\i query_93.sql
\o ../../analyze/analyze_94.json
\i query_94.sql
\o ../../analyze/analyze_95.json
\i query_95.sql
\o ../../analyze/analyze_96.json
\i query_96.sql
\o ../../analyze/analyze_97.json
\i query_97.sql
\o ../../analyze/analyze_98.json
\i query_98.sql
